name = "my-worker"
main = "cleaned-repo/my-worker/src/worker.js"
compatibility_date = "2025-09-05"

kv_namespaces = [
  { binding = "KV_TRANSCRIPTS", id = "3d75c1dbdbce4cfa9344028ed628539c" } # "binding": "BINDING_NAME"
]

[vars]
LLM_PROVIDER = "groq"
LLM_MODEL = "llama-3.1-70b-versatile"
LLM_BASE_URL = "https://api.groq.com/openai"
OPENAI_API_KEY = "{{ env.OPENAI_API_KEY }}"